# Generated by Django 3.0.7 on 2020-06-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.IntegerField(max_length=100)),
                ('stu_name', models.CharField(max_length=20)),
            ],
        ),
    ]
