# Generated by Django 3.0.7 on 2020-06-13 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0002_auto_20200613_2150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apiview',
            name='id',
        ),
        migrations.AlterField(
            model_name='apiview',
            name='stu_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
